name: form_floating_action_button
description: A Floating Action Button that can be used in forms to provide loading and validation feedback
version: 1.0.0
author: Jeff Peiffer <jpeiffer@gmail.com>
license: MIT
homepage: https://github.com/jpeiffer/form_floating_action_button

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any

flutter:
  uses-material-design: true
