name: form_floating_action_button
description: A Floating Action Button that can be used in forms to provide loading and validation feedback
version: 1.0.1
license: MIT
homepage: https://github.com/peiffer-innovations/form_floating_action_button

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
