name: Dart Pull Request Checker

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Dependencies
        run: flutter packages upgrade
      - name: Flutter Analyzer
        run: flutter analyze
      - name: Code Format
        run: dart format --set-exit-if-changed lib test
      - name: Run tests
        run: flutter test
